#!/bin/bash

. "$(dirname "$0")/cfut.sh" || { echo "cfut.sh not found"; exit 1; }
. tent.sh || { echo "tent.sh not found"; exit 1; }

printf "checking for $1 compiler version ... "
is_dn=false
for i in --version -v -V -qversion; do
  temp="$("${!2}" "$i" 2>/dev/null | head -n 1)"
  if [ -n "$temp" ]; then
    echo "$temp"
    zsconfuz-push result "compiler_${2}_vers=\"$temp\""
    is_dn=true
    break
  fi
done
$is_dn || echo "(none)"

printf "checking whether the $1 compiler works ... "
mkdir -p ".zscfzFiles"
tmpf=".zscfzFiles/compiler_ctst_$1.c"
cat > "$tmpf" <<EOF
int main() {}
EOF

"${!2}" -o ".zscfzFiles/compiler_ctst_$1.x" "$tmpf" &>/dev/null
print_result "compiler_${2}_works"
rm -f ".zscfzFiles/compiler_ctst_$1."* || true
