#!/bin/bash

if [[ -z $1 || -z $2 ]]; then
  echo "find_prog.sh VARNAME FOUND_VN ALTERNATIVES"
  exit 1
fi

. "$(dirname "$0")/cfut.sh" || { echo "cfut.sh not found"; exit 1; }

prog_found=false
var_name="$1"
found_vn="$2"
shift 2

for prog in ${!var_name} "$@"; do
  echo_n "checking for $prog ... "
  real_path=$(which "$prog" 2>/dev/null)
  if [ -f "$real_path" ]; then
    echo "$real_path"
    prog_found=true
    zsconfuz-push result "$var_name=$prog"
    break
  fi
  echo no
done

zsconfuz-push result "$found_vn=$prog_found"
