#!/bin/bash

if [[ -z $1 || -z $2 ]]; then
  echo "find_prog.sh VARNAME FOUND_VN ALTERNATIVES"
  exit 1
fi

echo_n() {
  printf '%s' "$@"
}

prog_found=false
var_name="$1"
found_vn="$2"
shift 2

for prog in ${!var_name} "$@"; do
  echo_n "checking for $prog ... "
  real_path=$(which "$prog" 2>/dev/null)
  if [ -f "$real_path" ]; then
    echo "$real_path"
    prog_found=true
    break
  fi
  echo no
done

printf "\000$found_vn=$prog_found\n"
$prog_found && printf "\000$var_name=$prog\n"
